import { Eye, Activity } from "lucide-react";
import { getSnapshot } from "@/lib/data/store";
import { formatCurrency, pluralize } from "@/lib/finance";
import { PageHead } from "@/components/dashboard/PageHead";
import { AdvisorChat } from "@/components/dashboard/AdvisorChat";
import { currentUserId } from "@/lib/auth";

export const dynamic = "force-dynamic";

export default async function AdvisorPage() {
  const userId = await currentUserId();
  if (!userId) return null;
  const s = await getSnapshot(userId);
  const live = Boolean(process.env.ANTHROPIC_API_KEY);

  return (
    <>
      <PageHead
        title="AI advisor"
        subtitle={
          live
            ? "Powered by Claude, grounded in your real numbers."
            : "Grounded in your real numbers. Add an API key for live Claude."
        }
      />

      <div className="grid-main">
        <div className="col">
          <AdvisorChat tall />
        </div>

        <div className="col">
          <section className="panel">
            <h2 className="ptitle">
              <Eye className="ic" size={16} aria-hidden />
              What it can see
            </h2>
            <div className="acct">
              <span>Safe to spend</span>
              <span className="amt tabular">{formatCurrency(s.safeToSpend)}</span>
            </div>
            <div className="acct">
              <span>Total liquidity</span>
              <span className="amt tabular">
                {formatCurrency(s.totalLiquidity)}
              </span>
            </div>
            <div className="acct">
              <span>Bills ({pluralize(s.billWindowDays, "day")})</span>
              <span className="amt tabular">
                {formatCurrency(s.upcomingBillsTotal)}
              </span>
            </div>
            <div className="acct">
              <span>Debt remaining</span>
              <span className="amt tabular">
                {formatCurrency(s.rescue.remaining)}
              </span>
            </div>
            {s.utilization && (
              <div className="acct">
                <span>Card utilization</span>
                <span className="amt tabular">
                  {Math.round(s.utilization.pct)}%
                </span>
              </div>
            )}
          </section>

          <section className="panel">
            <h2 className="ptitle">
              <Activity className="ic" size={16} aria-hidden />
              Status
            </h2>
            <span className={live ? "chip good" : "chip warn"}>
              {live ? "Live · Claude" : "Rule-based"}
            </span>
            <p
              style={{
                fontSize: 13,
                color: "var(--muted)",
                lineHeight: 1.55,
                marginTop: 12,
              }}
            >
              {live
                ? "Responses are generated by Claude using the snapshot above."
                : "Set ANTHROPIC_API_KEY to switch this advisor to live Claude — no other changes needed."}
            </p>
          </section>
        </div>
      </div>
    </>
  );
}
